Clear-Host
Get-Help about_Functions_Advanced_Methods
Get-Help about_Functions_Advanced_Parameters
Get-Help about_Functions_CmdletBindingAttribute
Get-Help about_Functions_OutputTypeAttribute
Get-Help about_Parameters